-- Extract Number From TEXT
DECLARE
	@String varchar(max) = '13May2022';

-- Method 1 
WITH POSITION AS
(SELECT 1 AS POS
UNION ALL SELECT POS + 1 FROM POSITION
WHERE POS < len(@String)
),
SELECT * FROM POSITION

CHARACTER AS(
SELECT Col FROM POSITION 
	CROSS APPLY 
	(SELECT Substring(@String, POS, 1)AS COL) AS Char1
)
SELECT * FROM CHARACTER

SELECT STRING_AGG(Col,'')
FROM CHARACTER
WHERE COL LIKE '[0-9]' -- For Numerics
-- WHERE COL LIKE '[aA-zA]'  For alphabets

-- Method 2
WITH CHARACTER AS(
SELECT STUFF(@String, 1, 1,'') AS REM_STR,
	LEFT(@String,1) AS Col
	SELECT UNION ALL(STUFF(REM_STR, 1, 1,'') AS REM_STR,
	LEFT(REM_STR,1) AS Col
			 FROM CHARACTER WHERE len(REM_STR) > 0)
)
SELECT REM_STR, Col FROM CHARACTER

SELECT STRING_AGG(Col,'')
FROM CHARACTER
WHERE COL LIKE '[0-9]' -- For Numerics
-- WHERE COL LIKE '[aA-zA]'  For alphabets